require "mcp/client/oauth"
require "securerandom"
require "timeout"
require "uri"
require_relative "../store/oauth_storage"

module AMG
  module Mcp
    # Bridges the mcp gem's OAuth::Flow — a single blocking call that expects
    # `redirect_handler` and `callback_handler` to run synchronously in one
    # thread — across AMG's admin console, where those two steps are
    # necessarily two separate HTTP requests: the admin clicks "Connect" (one
    # request), completes login at the third-party authorization server in a
    # new tab, and that server redirects back to AMG's own callback endpoint
    # (a second, unrelated request, possibly minutes later).
    #
    # `connect` runs Flow#run! in a background thread. Its `redirect_handler`
    # pushes the built authorization URL onto a queue that `connect` itself
    # is waiting on (bounded by CONNECT_TIMEOUT) so it can hand the URL back
    # in the HTTP response. Its `callback_handler` blocks (bounded by
    # CALLBACK_TIMEOUT, enforced by the queue never receiving a push past
    # that point — abandoned flows just leak one thread until process exit)
    # on a second queue that `complete` pushes into once the redirect
    # actually lands. `state` — unguessable, generated by the gem — is the
    # correlation key and doubles as CSRF protection, since the callback
    # endpoint has no session to authenticate the request with.
    class OAuthConnector
      CONNECT_TIMEOUT = 10

      class TimeoutError < StandardError; end

      Pending = Struct.new(:upstream_id, :callback_queue, :thread, keyword_init: true)

      def initialize
        @pending = {}
        @mutex = Mutex.new
      end

      # Starts the flow and returns the authorization URL the admin's
      # browser should be sent to.
      def connect(upstream:, db:, master_key:, public_url:)
        storage = Store::OAuthStorage.new(db: db, upstream_id: upstream[:id], master_key: master_key)
        redirect_uri = "#{public_url}/api/v1/upstreams/#{upstream[:id]}/oauth/callback"

        url_queue = Queue.new
        callback_queue = Queue.new
        provider = build_provider(
          upstream: upstream, storage: storage, redirect_uri: redirect_uri,
          on_redirect: ->(url) { url_queue.push(url.to_s) },
          on_callback: -> { callback_queue.pop }
        )

        thread = run_flow(upstream: upstream, provider: provider)
        url = wait_for_url(url_queue)
        register_pending(state_from(url), upstream[:id], callback_queue, thread)
        url
      end

      # Called from the public GET /oauth/callback route. `state` is the only
      # authentication this request has — it must match a `connect` call this
      # process itself started.
      def resume!(state, code)
        pending = @mutex.synchronize { @pending.delete(state) }
        return false unless pending

        pending.callback_queue.push([code, state])
        true
      end

      private

      def build_provider(upstream:, storage:, redirect_uri:, on_redirect:, on_callback:)
        client_info = storage.client_information
        MCP::Client::OAuth::Provider.new(
          client_metadata: {
            client_name: "AMG (#{upstream[:slug]})",
            redirect_uris: [redirect_uri],
            grant_types: %w[authorization_code refresh_token],
            response_types: ["code"],
            token_endpoint_auth_method: client_info ? "client_secret_post" : "none"
          },
          redirect_uri: redirect_uri,
          redirect_handler: on_redirect,
          callback_handler: on_callback,
          storage: storage
        )
      end

      def run_flow(upstream:, provider:)
        Thread.new do
          Thread.current.report_on_exception = false
          flow = MCP::Client::OAuth::Flow.new(provider: provider)
          flow.run!(server_url: upstream[:config]["url"])
        rescue StandardError => e
          AMG.logger&.error("amg: oauth connect failed for upstream #{upstream[:id]}: #{e.class}: #{e.message}")
        end
      end

      def register_pending(state, upstream_id, callback_queue, thread)
        @mutex.synchronize do
          @pending[state] = Pending.new(upstream_id: upstream_id, callback_queue: callback_queue, thread: thread)
        end
      end

      def state_from(url)
        URI.decode_www_form(URI(url).query.to_s).to_h["state"]
      end

      def wait_for_url(queue)
        Timeout.timeout(CONNECT_TIMEOUT) { queue.pop }
      rescue Timeout::Error
        raise TimeoutError, "timed out waiting for the authorization URL"
      end
    end
  end
end
